BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Tipologia" (
	"ID"	INTEGER,
	"Tipologia"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Referenti" (
	"ID"	INTEGER,
	"ID_Associazione"	INTEGER NOT NULL,
	"Nome"	TEXT NOT NULL,
	"MAILREFERENTE"	TEXT,
	FOREIGN KEY("ID_Associazione") REFERENCES "Associazioni"("ID") ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE("ID_Associazione","Nome"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "AltriSoggetti" (
	"ID"	INTEGER,
	"ID_Associazione"	INTEGER NOT NULL,
	"Nome"	TEXT NOT NULL,
	"MAILALTRISOGGETTI"	TEXT,
	FOREIGN KEY("ID_Associazione") REFERENCES "Associazioni"("ID") ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE("ID_Associazione","Nome"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Associazioni" (
	"ID"	INTEGER,
	"ID_TIPOLOGIA"	INTEGER NOT NULL,
	"COLONNA3"	TEXT,
	"TAVOLO"	BLOB NOT NULL CHECK("TAVOLO" IN (0, 1)),
	"DIRETTIVO_DELEGAZIONE"	INTEGER NOT NULL CHECK("DIRETTIVO_DELEGAZIONE" IN (0, 1)),
	"SOGGETTO"	TEXT NOT NULL UNIQUE,
	"CODICEFISCALE"	TEXT,
	FOREIGN KEY("ID_TIPOLOGIA") REFERENCES "Tipologia"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Mail" (
	"ID"	INTEGER,
	"IDAssociazione"	INTEGER NOT NULL,
	"Indirizzo"	TEXT NOT NULL,
	"PEC"	INTEGER DEFAULT 0 CHECK("PEC" IN (0, 1)),
	"Predefinito"	INTEGER DEFAULT 0 CHECK("Predefinito" IN (0, 1)),
	FOREIGN KEY("IDAssociazione") REFERENCES "Associazioni"("ID") ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE("IDAssociazione","Indirizzo"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Runts" (
	"CodiceFiscale"	TEXT UNIQUE,
	"Denominazione"	TEXT,
	"Cognome"	TEXT,
	"Nome"	TEXT,
	"IDAssociazione"	INTEGER,
	"Provincia"	TEXT,
	PRIMARY KEY("CodiceFiscale")
);
CREATE TABLE IF NOT EXISTS "Telefono" (
	"ID"	INTEGER,
	"IDAssociazione"	INTEGER NOT NULL,
	"Telefono"	TEXT NOT NULL,
	"Predefinito"	INTEGER DEFAULT 0,
	FOREIGN KEY("IDAssociazione") REFERENCES "Associazioni"("ID") ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE("IDAssociazione","Telefono"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CesvotTelefono" (
	"ID"	INTEGER,
	"Denominazione"	TEXT,
	"Telefono"	TEXT,
	UNIQUE("Denominazione","Telefono"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CesvotMail" (
	"ID"	INTEGER,
	"Denominazione"	TEXT,
	"Mail"	TEXT,
	UNIQUE("Denominazione","Mail"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Temporanea" (
	"SOGGETTO"	TEXT,
	"MAIL"	TEXT
);
CREATE TABLE IF NOT EXISTS "MailList" (
	"ID"	INTEGER NOT NULL,
	"Descrizione"	TEXT NOT NULL UNIQUE,
	"Note"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ListaMail" (
	"ID"	INTEGER,
	"IDListaMail"	INTEGER NOT NULL,
	"IDMail"	INTEGER NOT NULL,
	"TipoInvio"	TEXT DEFAULT 'CCN',
	FOREIGN KEY("IDMail") REFERENCES "Mail"("ID") ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE("IDListaMail","IDMail"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "AgoraTipoEvento" (
	"ID"	INTEGER NOT NULL,
	"IntestazionePagina"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Agora" (
	"ID"	INTEGER NOT NULL,
	"Data"	TEXT NOT NULL,
	"Evento"	TEXT,
	"ODG"	TEXT,
	"Verbale"	TEXT,
	"Documenti"	TEXT,
	"IDTipoEvento"	INTEGER NOT NULL,
	FOREIGN KEY("IDTipoEvento") REFERENCES "AgoraTipoEvento"("ID") ON DELETE RESTRICT,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "AgoraPresenti" (
	"ID"	INTEGER,
	"IDRiunioni"	INTEGER NOT NULL,
	"IDAssociazione"	INTEGER NOT NULL,
	"Rappresentante"	TEXT,
	FOREIGN KEY("IDAssociazione") REFERENCES "Associazioni"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("IDRiunioni") REFERENCES "Agora"("ID") ON UPDATE CASCADE ON DELETE CASCADE,
	UNIQUE("IDRiunioni","IDAssociazione","Rappresentante"),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Utenti" (
	"ID"	INTEGER,
	"Nome"	TEXT,
	"Email"	TEXT UNIQUE,
	"Password"	TEXT,
	"Amministratore"	INTEGER DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "AgoraOld" (
	"ID"	INTEGER NOT NULL,
	"Data"	TEXT NOT NULL,
	"Evento"	TEXT,
	"ODG"	TEXT,
	"Verbale"	TEXT,
	"Documenti"	TEXT,
	"IDTipoEvento"	INTEGER NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Report" (
	"ID"	INTEGER NOT NULL,
	"Password"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "DocumentoTipo" (
	"ID"	INTEGER NOT NULL,
	"Tipo"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Documento" (
	"ID"	INTEGER,
	"IDTipologia"	INTEGER NOT NULL,
	"IDTipo"	INTEGER NOT NULL,
	"Nome"	TEXT NOT NULL,
	"Link"	TEXT NOT NULL,
	"Note"	TEXT,
	FOREIGN KEY("IDTipo") REFERENCES "DocumentoTipo"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("IDTipologia") REFERENCES "Tipologia"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_mail" ON "Mail" (
	"IDAssociazione",
	"Indirizzo"
);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_documento_univoco" ON "Documento" (
	"Nome",
	"IDTipologia",
	"IDTipo"
);
COMMIT;
